global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'MyBot'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
#  - job_name: 'nodeexporter'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['nodeexporter:9100']
#
#  - job_name: 'cadvisor'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['cadvisor:8080']
#
#  - job_name: 'prometheus'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['localhost:9090']
#
#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    honor_labels: true
#    static_configs:
#      - targets: ['pushgateway:9091']
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['13.53.105.240:9100']
        labels:
          vm: uu-web
      - targets: ['13.48.6.98:9100']
        labels:
          vm: uu-go

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['13.53.105.240:9338']
        labels:
          vm: uu-web
      - targets: ['13.48.6.98:9338']
        labels:
          vm: uu-go

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
